/** Bengali (default app language) UI strings used as locators. */
export const bn = {
  appName: "ইউনিভার্সাল বিজনেস ওএস",
  signIn: "সাইন ইন করুন",
  createBusinessBtn: "ব্যবসা তৈরি করুন",
  register: "রেজিস্টার",
  login: "লগইন",
  logout: "লগআউট",
  phone: "ফোন নম্বর",
  password: "পাসওয়ার্ড",
  name: "নাম",
  businessName: "ব্যবসার নাম",
  businessSetup: "ব্যবসা সেটআপ",
  shopSetup: "শপ সেটআপ",
  shopName: "শপের নাম",
  branchCode: "ব্রাঞ্চ কোড",
  createShop: "শপ তৈরি করুন",
  settings: "সেটিংস",
  dashboard: "ড্যাশবোর্ড",
  products: "পণ্য",
  customers: "কাস্টমার",
  suppliers: "সাপ্লায়ার",
  invalidLogin: "ভুল ফোন নম্বর বা পাসওয়ার্ড",
};
